[build]
  command = "ng build && ng run pokemon-ssr-jdc:server"
  publish = "dist/pokemon-ssr-jdc/browser"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

